// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAFwYUJaQ41btDluKcuv3HyCGRl6sxe6M',
    appId: '1:66680007741:web:afefc24eb3c5f6b73fce54',
    messagingSenderId: '66680007741',
    projectId: 'notesapp-1eab1',
    authDomain: 'notesapp-1eab1.firebaseapp.com',
    storageBucket: 'notesapp-1eab1.appspot.com',
    measurementId: 'G-06YF5TBRV1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBit3xmbOBwbAiRkiNYW4jnFGWB1EJL5xA',
    appId: '1:66680007741:android:d024d281c154cbee3fce54',
    messagingSenderId: '66680007741',
    projectId: 'notesapp-1eab1',
    storageBucket: 'notesapp-1eab1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhfrBnq7RxYb2h5loXYUKCgqM-eAppVsI',
    appId: '1:66680007741:ios:bf51b9e960b4c45c3fce54',
    messagingSenderId: '66680007741',
    projectId: 'notesapp-1eab1',
    storageBucket: 'notesapp-1eab1.appspot.com',
    iosClientId: '66680007741-7t3vgm1e36v4gks6b9uqkregcblnbe0t.apps.googleusercontent.com',
    iosBundleId: 'com.example.myNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhfrBnq7RxYb2h5loXYUKCgqM-eAppVsI',
    appId: '1:66680007741:ios:d72e2b199c0eeefe3fce54',
    messagingSenderId: '66680007741',
    projectId: 'notesapp-1eab1',
    storageBucket: 'notesapp-1eab1.appspot.com',
    iosClientId: '66680007741-sssvfdf70rb5q1vpn06s0l24m4u9mp73.apps.googleusercontent.com',
    iosBundleId: 'com.example.myNotes.RunnerTests',
  );
}
